
int copyLSB(int);
int test_copyLSB(int);
int conditional(int, int, int);
int test_conditional(int, int, int);
int allEvenBits();
int test_allEvenBits();
int implication(int, int);
int test_implication(int, int);
int replaceByte(int, int, int);
int test_replaceByte(int, int, int);
int tmin();
int test_tmin();
int minusOne();
int test_minusOne();
int isGreater(int, int);
int test_isGreater(int, int);
int isAsciiDigit(int);
int test_isAsciiDigit(int);
int howManyBits(int);
int test_howManyBits(int);
int greatestBitPos(int);
int test_greatestBitPos(int);
int satMul3(int);
int test_satMul3(int);
int subOK(int, int);
int test_subOK(int, int);
unsigned float_neg(unsigned);
unsigned test_float_neg(unsigned);
unsigned float_i2f(int);
unsigned test_float_i2f(int);
