
int bitXor(int, int);
int test_bitXor(int, int);
int bitParity(int);
int test_bitParity(int);
int anyOddBit();
int test_anyOddBit();
int logicalShift(int, int);
int test_logicalShift(int, int);
int rotateRight(int, int);
int test_rotateRight(int, int);
int bang(int);
int test_bang(int);
int tmax();
int test_tmax();
int absVal(int);
int test_absVal(int);
int divpwr2(int, int);
int test_divpwr2(int, int);
int ezFiveEighths(int);
int test_ezFiveEighths(int);
int isPositive(int);
int test_isPositive(int);
int isLessOrEqual(int, int);
int test_isLessOrEqual(int, int);
int ilog2(int);
int test_ilog2(int);
unsigned float_half(unsigned);
unsigned test_float_half(unsigned);
int float_f2i(unsigned);
int test_float_f2i(unsigned);
